name: Bug Report
description: Report a bug, crash, or unexpected behavior in the mod.
title: "[BUG] <Concise summary of the issue>"
labels: bug, needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please fill out the template below completely.

  - type: textarea
    id: description
    attributes:
      label: Description of the Bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you saw happen.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List exact steps to reproduce the behavior. Be as specific as possible.
      placeholder: |
        1. Start a skirmish game on the 'Great Plains' map.
        2. Select the 'Dutch' civilization.
        3. Research the 'Economic Theory' technology in the Industrial Age.
        4. The game crashes/unit is disabled.
    validations:
      required: true

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: Expected vs. Actual Behavior
      description: What did you expect to happen, and what actually happened?
      placeholder: |
        Expected: The game should not crash; the unit should gain the listed bonus.
        Actual: Game crashed/The unit received no bonus.
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: The exact version of the mod you are using (e.g., v1.5, Alpha 3).
      placeholder: e.g. v1.2.0

  - type: input
    id: game_version
    attributes:
      label: Game Version (Host Game)
      description: The version of the base game (e.g., the last four digits of the build number).
      placeholder: e.g. 100.12.5550.0

  - type: checkboxes
    id: checklist
    attributes:
      label: Final Checklist
      options:
        - label: I have searched the existing issues to ensure this bug has not already been reported.
          required: true
        - label: I have attached a screenshot or log file (if applicable).